# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PROD pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: "docker build . --tag immassive/devops:${{github.run_number}}"

    - name: Push Docker Image to DockerHub
      run: "docker push immassive/devops:${{github.run_number}}"
    
    - name: SSH to server and redeploy
      uses: appleboy/ssh-action@master
      with:
        host: 107.21.71.63
        username: ubuntu
        key: ${{ secrets.P_KEY }}
        port: 22
        script: |
          sudo docker ps -q --filter "name=devops" | grep -q . && sudo docker container stop devops && sudo docker container rm -fv devops
          sudo sleep 15
          sudo docker run -d -p 8084:8084 --name devops immassive/devops:latest